env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"

task:
  name: Test
  skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 30m
  container:
    image: apon77/aosp:cirrus
    cpu: 2
    memory: 4G
  env_script:
    - env
  test_script:
    - set -e
    - bash test.sh

    #

