test_task:
  container:
    image: apon77/aosp:ccache
  test_script:
    - bash test.sh
task:
  name: Build
  depends_on:
    - test
  env:
    USE_CCACHE: 1
    ROM_NAME: "grep init build_rom.sh | cut -d / -f 4"
  timeout_in: 4h
  persistent_worker:
    isolation:
      container:
        image: apon77/aosp:ccache
        cpu: 8
        memory: 40g
        volumes:
          - /home/cirrus/roms:/home/ci/roms
          - /home/cirrus/ccache:/home/ci/ccache
          - /home/cirrus/.config:/home/ci/.config
  build_script:
    - mkdir -p ~/roms/$(bash -c "$ROM_NAME")
    - cd ~/roms/$(bash -c "$ROM_NAME")
    - rm -rf .repo/local_manifests
    - export CCACHE_DIR=/home/ci/ccache/$(bash -c "$ROM_NAME")
    - ccache -z
    - bash $CIRRUS_WORKING_DIR/build_rom.sh
    - ccache -s
    - rm -rf out/target/product/$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh | cut -d _ -f 2 | cut -d - -f 1)
