task:
  name: Build
  persistent_worker: {}
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
  env_script:
    - env
  sync_script:
    - bash sync_rom.sh
  build_script:
    - bash build_rom.sh
  upload_script: 
    - bash upload_rom.sh
