env:
    MANIFEST: https://github.com/Evolution-X/manifest.git -b tiramisu --depth=1
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/ij-israfil/local_manifest.git
    TARGET: evolution 
    LUNCH_COMBO: evolution_${DEVICE}-userdebug
    OUTPUT: e*.zip
    #CLO: drivex1:AppDrive
    #CLO_1: ENCRYPTED[!a58fc3c6199cc26bd840c8905e8ac41aac52f41609791f60db8cacba7889c523b70ebe2a6639e864f0d34715f0d1e3bc!]
    URI: https://sourceforge.net/projects/evox1/files/cache/ccache.tar.gz/download
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./ci/sync.sh
  Build_script:
      - ./ci/build.sh
  upload_script:
      - ./scripts/upl0ad
