env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    bot_api: "ENCRYPTED[b16032643ad0994cda4822c9d477956f434278d0f786f8e131b585aa4f8510a11f3cd9f6a66a63568d2cba1c4dde25b4]"

task:
  name: Test
  skip: $CIRRUS_BRANCH == 'main'
  only_if: $CIRRUS_REPO_OWNER == 'ROM-builders'
  timeout_in: 2m
  persistent_worker:
    labels:
      name: AX61-2
    isolation:
      container:
        image: apon77/aosp:cirrus
        cpu: 2
        memory: 4G

  env_script:
    - env
  show_script:
    - cat $CIRRUS_WORKING_DIR/build_rom.sh
  notify_script:
    - rom_name=Project-Nova-UI
    - branch_name=11
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-17.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-15.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - device=RMX1831
    - grep _jasmine_sprout $CIRRUS_WORKING_DIR/build_rom.sh > /dev/null && device=jasmine_sprout
    - your_telegram_id=@ROM_builders_junk
    - show=$(cat $CIRRUS_WORKING_DIR/build_rom.sh)
    - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" -d "text=<code>$device-$rom_name</code> Started
      
      https://cirrus-ci.com/build/$CIRRUS_BUILD_ID
      
      $show" -d "chat_id=${your_telegram_id}" -d "parse_mode=HTML"
  test_script:
    - set -e
    - curl -Ls https://github.com/ROM-builders/temporary/raw/main/test.sh | bash

task:
  name: Build
  skip: $CIRRUS_BRANCH == 'main'
  only_if: $CIRRUS_REPO_OWNER == 'ROM-builders'
  depends_on:
    - Test
  timeout_in: 4h
  persistent_worker:
    labels:
      name: AX61-1
    isolation:
      container:
        image: apon77/aosp:cirrus
        cpu: 24
        memory: 120G
        volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config

  show_script:
    - cat $CIRRUS_WORKING_DIR/build_rom.sh
  sync_script:
    - set -e
    - rom_name=Project-Nova-UI
    - branch_name=11
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-17.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-15.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - mkdir -p ~/roms/$rom_name
    - cd ~/roms/$rom_name
    - rm -rf .repo/local_manifests
    - command="repo init --depth=1 --no-repo-verify -u git://github.com/Project-Nova-UI/manifest.git -b 11 -g default,-device,-mips,-darwin,-notdefault && git clone https://github.com/Jamesgosling2004/local_manifest.git --depth 1 -b master .repo/local_manifests && repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8"
    - only_sync="repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8"
    - (bash -c "$command" | tee sync.txt) || (grep '^fatal: remove-project element specifies non-existent project' sync.txt && exit 1) || (repo forall -c 'git checkout .' && bash -c "$only_sync") || (find -name shallow.lock -delete && find -name index.lock -delete && bash -c "$only_sync")
    - rm -rf sync.txt

  build_script:
    - set -e
    - rom_name=Project-Nova-UI
    - branch_name=11
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-17.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-15.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - device=RMX1831
    - grep _jasmine_sprout $CIRRUS_WORKING_DIR/build_rom.sh > /dev/null && device=jasmine_sprout
    - cd ~/roms/$rom_name
    - export CCACHE_DIR=~/ccache/$rom_name/$device
    - export CCACHE_EXEC=$(which ccache)
    - export USE_CCACHE=1
    - ccache -M 10G
    - ccache -z
    - ls device/*/*/vendorsetup.sh && echo "Please remove vendorsetup.sh file from device tree, use local manifest for cloning and removing repositories." && exit 1 || true
    - command="source build/envsetup.sh && lunch lineage_RMX1831-userdebug && brunch RMX1831"
    - bash -c "$command"

  ccache_stats_script:
    - set -e
    - rom_name=Project-Nova-UI
    - branch_name=11
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-17.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-15.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - device=RMX1831
    - grep _jasmine_sprout $CIRRUS_WORKING_DIR/build_rom.sh > /dev/null && device=jasmine_sprout
    - export CCACHE_DIR=~/ccache/$rom_name/$device
    - ccache -s

  upload_script:
    - set -e
    - rom_name=Project-Nova-UI
    - branch_name=11
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-17.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-15.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - device=RMX1831
    - grep _jasmine_sprout $CIRRUS_WORKING_DIR/build_rom.sh > /dev/null && device=jasmine_sprout
    - cd ~/roms/$rom_name
    - engzip=$(ls out/target/product/$device/*-eng*.zip || true)
    - otazip=$(ls out/target/product/$device/*-ota-*.zip | grep -v "hentai" | grep -v "evolution" || true)
    - awaken=$(ls out/target/product/$device/Project-Awaken*.zip || true)
    - octavi=$(ls out/target/product/$device/OctaviOS-R*.zip || true)
    - p404=$(ls out/target/product/$device/?.*zip || true)
    - rm -rf $engzip $otazip $awaken $octavi $p404
    - dlink=$(basename out/target/product/$device/*.zip)
    - command="rclone copy out/target/product/RMX1831/*.zip cirrus:RMX1831 -P"
    - if [[ $device == jasmine_sprout ]]; then command="rclone copy out/target/product/jasmine_sprout/*zip cirrus:jasmine_sprout -P"; fi
    - bash -c "$command"
    - echo "Download link https://roms.cirrus-ci.workers.dev/0:/$device/$dlink"

  remove_script:
    - set -e
    - rom_name=Project-Nova-UI
    - branch_name=11
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-17.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-15.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - device=RMX1831
    - grep _jasmine_sprout $CIRRUS_WORKING_DIR/build_rom.sh > /dev/null && device=jasmine_sprout
    - cd ~/roms/$rom_name
    - rm -rf out/target/product/$device

task:
  name: Post Build
  skip: $CIRRUS_BRANCH == 'main'
  only_if: $CIRRUS_REPO_OWNER == 'ROM-builders'
  skip_notifications: true
  depends_on:
    - Build
  timeout_in: 2m
  persistent_worker:
    labels:
      name: AX61-2
    isolation:
      container:
        image: apon77/aosp:cirrus
        cpu: 2
        memory: 4G

  post_build_script:
    - set -e
    - rom_name=Project-Nova-UI
    - branch_name=11
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-17.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - if [[ $rom_name == LineageOS ]]; then if [[ $branch_name == lineage-15.1 ]]; then rom_name=$rom_name-$branch_name; fi; fi
    - device=RMX1831
    - grep _jasmine_sprout $CIRRUS_WORKING_DIR/build_rom.sh > /dev/null && device=jasmine_sprout
    - your_telegram_id=@ROM_builders_channel
    - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" -d "text=<code>$device-$rom_name</code> Succeed
      
      https://cirrus-ci.com/build/$CIRRUS_BUILD_ID" -d "chat_id=${your_telegram_id}" -d "parse_mode=HTML"
