task:
  name: Build
  persistent_worker:
    isolation:
      container:
        image: Sohang85/xdroid:latest
        cpu: 8
        memory: 40G
        volumes:
          - /tmp/whyred-xdroid-Sohang85:/tmp/whyred-xdroid-Sohang85
          - /home/cirrus/.ccache:/home/ci/.ccache
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/whyred-xdroid-Sohang85
  clone_script:
    - repo init --depth=1 -u repo init -u https://github.com/xdroid-oss/xd_manifest -b twelve || true
  sync_script:
    - rm -rf .repo/local_manifests || true
    - git clone https://github.com/Sohang85/Local_Manifest.git --depth 1 -b whyred-xdroid .repo/local_manifests
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync
  build_script:
    - . build/envsetup.sh
    - lunch xd_whyred-userdebug
    - make xd 
  ccache_stats_script:
    - ccache -s

