env:
    # Manifest
    MANIFEST: https://github.com/PixelExperience/manifest.git
    MANIFEST_BRANCH: eleven

    # Device
    DT_LINK: https://github.com/Sushrut1101-ROMs/device_xiaomi_garden.git
    DEVICE: garden
    OEM: xiaomi
    LUNCH_COMBO: aosp_garden-eng
    TARGET: bacon

    DT_PATH: device/$OEM/$DEVICE
    OUTPUT: PixelExperience*.zip

    # Extra Command
    EXTRA_CMD: export SKIP_ABI_CHECKS=true

    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Full (absolute) path. Use "$HOME" instead of "~".
    USE_CCACHE: 1
    CCACHE_SIZE: 50G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 48

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

    # Telegram
    TG_CHAT_ID: ENCRYPTED[0003e1cf5276424a5b2afb8c6a39f2d830864e8555b37220bd3bf173f3ef5b8769ab98425d96a76adf64b18241c940dd]
    TG_TOKEN: ENCRYPTED[03de4105db5d23ec42490965c0a0f79217c1e3366cb152bd9d9a045e22586eba675615e1f08bf1aea3e860d499efde60]

task:
  name: "AOSP Build"
  trigger_type: manual
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 24
      memory: 120G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash upload.sh