task:
  name: Build
  persistent_worker: {}
  container:
    image: apon77/aosp:latest
    cpu: 8
    memory: 24G
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
  env_script:
    - env
  sync_script:
    - rm -rf .repo/local_manifests || true
    - bash sync_rom.sh
  build_script:
    - bash build_rom.sh
  ccache_stats_script:
    - ccache -s
  upload_script:
    - bash upload_rom.sh
