env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"

task:
  name: Test
  skip: $CIRRUS_BRANCH == 'main'
  only_if: $CIRRUS_REPO_OWNER == 'ROM-builders'
  timeout_in: 30m
  container:
    image: apon77/aosp:cirrus
    cpu: .7
    memory: 2G
  env_script:
    - env
  show_script:
    - cat $CIRRUS_WORKING_DIR/build_rom.sh
  notify_script:
    - rom_name=$(grep init $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d / -f 4)
    - device=$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)
    - bot_api=1659341938:AAHi4nlqvClbSodeGmLWlM044Xti9Y_HK_Y
    - your_telegram_id=571213272
    - show=$(cat $CIRRUS_WORKING_DIR/build_rom.sh)
    - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" -d "text=<code>$device-$rom_name</code> Started
      
      https://cirrus-ci.com/build/$CIRRUS_BUILD_ID
      
      $show" -d "chat_id=${your_telegram_id}" -d "parse_mode=HTML"
  test_script:
    - set -e
    - curl -Ls https://github.com/ROM-builders/temporary/raw/main/test.sh | bash

task:
  name: Build
  skip: $CIRRUS_BRANCH == 'main'
  only_if: $CIRRUS_REPO_OWNER == 'ROM-builders'
  depends_on:
    - Test
  timeout_in: 4h
  persistent_worker:
    isolation:
      container:
        image: apon77/aosp:cirrus
        cpu: 24
        memory: 60G
        volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config

  sync_script:
    - set -exv

    - rom_name=$(grep init $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d / -f 4)

    - mkdir -p ~/roms/$rom_name
    - cd ~/roms/$rom_name
    - rm -rf .repo/local_manifests
    - repo forall -c "git checkout ." || true
    - find -name shallow.lock -delete
    - find -name index.lock -delete
    - command=$(head $CIRRUS_WORKING_DIR/build_rom.sh -n $(expr $(grep 'build/envsetup.sh' $CIRRUS_WORKING_DIR/build_rom.sh -n | cut -f1 -d:) - 1))
    - bash -c "$command"

  build_script:
    - set -exv

    - rom_name=$(grep init $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d / -f 4)
    - device=$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)

    - cd ~/roms/$rom_name
    - export CCACHE_DIR=~/ccache/$rom_name/$device
    - export CCACHE_EXEC=$(which ccache)
    - export USE_CCACHE=1
    - ccache -M 10G
    - ccache -z
    - rm -rf device/*/*/vendorsetup.sh
    - command=$(tail $CIRRUS_WORKING_DIR/build_rom.sh -n +$(expr $(grep 'build/envsetup.sh' $CIRRUS_WORKING_DIR/build_rom.sh -n | cut -f1 -d:) - 1)| head -n -1 | grep -v 'rclone copy')
    - bash -c "$command"

  ccache_stats_script:
    - set -exv
    - rom_name=$(grep init $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d / -f 4)
    - device=$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)

    - export CCACHE_DIR=~/ccache/$rom_name/$device
    - ccache -s

  upload_script:
    - set -exv
    - rom_name=$(grep init $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d / -f 4)
    - device=$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)

    - cd ~/roms/$rom_name
    - engzip=$(ls out/target/product/$device/*eng*.zip || true )
    - otazip=$(ls out/target/product/$device/*-ota-*.zip || true )
    - rm -rf $engzip $otazip
    - dlink=$(basename out/target/product/$device/*.zip)
    - command=$(grep 'rclone copy' $CIRRUS_WORKING_DIR/build_rom.sh)
    - bash -c "$command"
    - echo "Downlod link https://roms.cirrus-ci.workers.dev/0:/$device/$dlink"

  remove_script:
    - set -exv
    - rom_name=$(grep init $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d / -f 4)
    - device=$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)
    - cd ~/roms/$rom_name
    - repo forall -c "git checkout ." || true
    - rm -rf out/target/product/$device

task:
  name: Post Build
  skip: $CIRRUS_BRANCH == 'main'
  only_if: $CIRRUS_REPO_OWNER == 'ROM-builders'
  skip_notifications: true
  depends_on:
    - Build
  timeout_in: 30m
  container:
    image: apon77/aosp:cirrus
    cpu: .7
    memory: 2G
  post_build_script:
    - set -e
    - rom_name=$(grep init $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d / -f 4)
    - device=$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)
    - bot_api=1659341938:AAHi4nlqvClbSodeGmLWlM044Xti9Y_HK_Y
    - your_telegram_id=@ROM_builders_channel
    - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" -d "text=<code>$device-$rom_name</code> Succeed
      
      https://cirrus-ci.com/build/$CIRRUS_BUILD_ID" -d "chat_id=${your_telegram_id}" -d "parse_mode=HTML"