task:
  name: Build
  persistent_worker:
    isolation:
      container:
        image: apon77/aosp:latest
        cpu: 8
        memory: 40g
        volumes:
          - /home/cirrus:/tmp/home
  check_script:
    - repo init --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x
    - repo sync vendor/aosp

test_task:
  container:
    image: apon77/aosp:ccache
  test_script:
    - set -exv
    - repo init --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x
    - repo sync vendor/aosp
