env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"

task:
  name: Test
  only_if: $CIRRUS_REPO_OWNER == 'ROM-builders'
  timeout_in: 30m
  persistent_worker:
    labels:
      name: AX61-2
    isolation:
      container:
        image: apon77/aosp:cirrus
        cpu: 2
        memory: 4G
  test_script:
    - pwd && ls -lhA && ls -lhA ..
    - echo $CIRRUS_REPO_OWNER
    - echo $CIRRUS_WORKING_DIR
