task:
  name: Build
  persistent_worker: {}
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
  env_script:
    - env
  clone_script:
    - repo init --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x || true
  sync_script:
    - rm -rf .repo/local_manifests || true
    - git clone https://github.com/yashlearnpython/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
  build_script:
    - source build/envsetup.sh
    - lunch aosp_mido-user
    - m aex -j$(nproc --all)
  ccache_stats_script:
    - ccache -s
  upload_script: |
    up() {
      curl --upload-file $1 https://transfer.sh/$(basename $1); echo
      # 14 days, 10 GB limit
    }

    up out/target/product/mido/*.zip
