#!/bin/bash
CIRRUS_WORKING_DIR=~/temporary
url=https://$(grep init $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d / -f 3-5 | cut -d ' ' -f 1)
rom_name=$(grep init $CIRRUS_WORKING_DIR/build_rom.sh -m 1 | cut -d / -f 4)
#echo $url $rom_name
#url=https://$(echo hi)
curl -Ls $url 2>&1 | grep 'repo init' | grep $rom_name | wc -l
