#!/bin/bash
chk() {
df -h
nproc
env
}
sudo apt update &&sudo apt install pigz wget
sudo apt install jq -y
sudo apt upgrade
c_down() {
cd /tmp
time aria2c $URI -x16 -s50
time tar xf ccache.tar.gz
}

echo "Checking free space"
chk
echo "Downloading ccache"
c_down
echo "Done"
